version: 2

sources:
  - name: aws_data_lake
    database: awsdatacatalog
    schema: us_flight_database
    tables:
      - name: clean_geo
        external:
          location: "s3://{{ env_var('TARGET_S3_BUCKET') }}/clean/geo/"
          file_format: parquet
        columns:
          - name: iata_code
            datatype: string
            description: airport code
            tests:
              - not_null
          - name: airport
            datatype: string
            description: name of the airport
          - name: city
            datatype: string
            description: city
          - name: state
            datatype: string
            description: name of state of country
          - name: country
            datatype: string
            description: name of the country
            tests:
              - accepted_values:
                  values: ['USA']
          - name: latitude
            datatype: float
          - name: longitude
            datatype: float

      - name: clean_weather
        external:
          location: "s3://{{ env_var('TARGET_S3_BUCKET') }}/clean/weather/"
          file_format: parquet
        columns:
          - name: airport_id
            datatype: string
            description: airport code
            tests:
              - not_null
          - name: time
            datatype: string      
            description: date
            tests:
              - not_null
          - name: tavg
            datatype: float
            description: average temperature
          - name: prcp
            datatype: float
            description: Total Precipitation (mm)
          - name: snow
            datatype: float
            description: snow depth
          - name: wspd
            datatype: float
            description: Average Wind Speed (km/h)
          - name: pres
            datatype: float
            description: Sea-Level Air Pressure (hPa)
            
      - name: clean_flights
        description: "Raw flight data from Spark"
        external:
          location: "s3://{{ env_var('TARGET_S3_BUCKET') }}/clean/flights/"
          file_format: parquet
        columns:
          - name: flightdate
            data_type: string     
          - name: day_of_week
            data_type: int
          - name: airline
            data_type: string
          - name: tail_number
            data_type: string
          - name: dep_airport
            data_type: string
          - name: dep_cityname
            data_type: string
          - name: deptime_label
            data_type: string
          - name: dep_delay
            data_type: int
          - name: dep_delay_tag
            data_type: int
          - name: dep_delay_type
            data_type: string
          - name: arr_airport
            data_type: string
          - name: arr_cityname
            data_type: string
          - name: arr_delay
            data_type: int
          - name: arr_delay_type
            data_type: string
          - name: flight_duration
            data_type: int
          - name: distance_type
            data_type: string
          - name: delay_carrier
            data_type: int
          - name: delay_weather
            data_type: int
          - name: delay_nas
            data_type: int
          - name: delay_security
            data_type: int
          - name: delay_lastaircraft
            data_type: int
          - name: manufacturer
            data_type: string
          - name: model
            data_type: string
          - name: aircraft_age
            data_type: int

      - name: clean_cancelled_diverted
        description: "Raw cancelled/diverted data from Spark"
        external:
          location: "s3://{{ env_var('TARGET_S3_BUCKET') }}/clean/cancelled_diverted/"
          file_format: parquet
        columns:
          - name: flightdate
            data_type: string     
          - name: day_of_week
            data_type: int
          - name: airline
            data_type: string
          - name: tail_number
            data_type: string
          - name: cancelled
            data_type: int
          - name: diverted
            data_type: int
          - name: dep_airport
            data_type: string
          - name: dep_cityname
            data_type: string
          - name: deptime_label
            data_type: string
          - name: dep_delay
            data_type: int
          - name: dep_delay_tag
            data_type: int
          - name: dep_delay_type
            data_type: string
          - name: arr_airport
            data_type: string
          - name: arr_cityname
            data_type: string
          - name: arr_delay
            data_type: int
          - name: arr_delay_type
            data_type: string
          - name: flight_duration
            data_type: int
          - name: distance_type
            data_type: string
          - name: delay_carrier
            data_type: int
          - name: delay_weather
            data_type: int
          - name: delay_nas
            data_type: int
          - name: delay_security
            data_type: int
          - name: delay_lastaircraft
            data_type: int
