us_flight_analytics:
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://us-flight-delay-analytics-athena-result/prefix/
      
      s3_data_dir: s3://us-flight-delay-analytics-athena-result/business/
      
      
      region_name: ap-southeast-1
      database: awsdatacatalog
      schema: us_flight_database
      data_catalog: awsdatacatalog
      threads: 4
      
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      
  target: dev