us_flight_analytics:
  outputs:
    dev:
      type: athena
      # Get variable from docker
      s3_staging_dir: "{{ env_var('S3_ATHENA_RESULT') }}"
      s3_data_dir: "{{ env_var('S3_BUCKET_FINAL_RESULT') }}"
      region_name: ap-southeast-1
      database: awsdatacatalog
      schema: "{{ env_var('DATABASE_NAME') }}"
      work_group: primary
      data_catalog: AwsDataCatalog
      threads: 4
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  target: dev
